function initLsOptGui(cmdStr,value);

if nargin==0,
   global OptimGuiHandle;
   cmdStr='start';
   if isempty('OptimGuiHandle');
      OptimGuiHandle=gcf;
   end
   value=OptimGuiHandle;
   figure(gcf);
   clf;
end
if strcmp(cmdStr,'start')
  % When we enter here the screen has been cleared.
  global noParEdit
  OptimGuiHandle=value;
  uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[38 70 26 8]/100,...
      'String','Initialization of the LSOptGUI. What do you want to do?');
  uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[35 56 30 4]/100,...
      'String','Start a new optimization');
   uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[20 50 29 4]/100,...
      'String','How many parameters (1-20)');
   noParEdit= uicontrol(OptimGuiHandle,'Style','edit',...
      'Units','normalized',...
      'Position',[51 49 10 5]/100,...
      'String','4','Callback','initLsOptGui(''inputParameterNames'')');
   uicontrol(OptimGuiHandle,'Style','pushbutton',...
      'Units','normalized','Position',[63 49 9 5]/100,...
      'String','GO!',...
      'Callback','initLsOptGui(''inputParameterNames'')');
   uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[35 26 30 4]/100,...
      'String','Load an old set of parameters');
   uicontrol(OptimGuiHandle,'Style','pushbutton',...
      'Units','normalized','Position',[35 19 30 5]/100,...
      'String','Load old PARAMETERS',...
      'Callback','initLsOptGui(''loadFile'');');
elseif strcmp(cmdStr,'loadFile'),
   [fileName,fileDir]=uigetfile('*.mat','Load PARAMETER file');
   if fileName~=0
      global PARAMETERS
      eval(['load ' fileDir fileName]); 
      lsoptgui('Initialize');
   end
elseif strcmp(cmdStr,'inputParameterNames')
  global OptimGuiHandle noParEdit PARAMETERS
  PARAMETERS.noParameters=str2num(get(noParEdit,'String'));
  if ceil(PARAMETERS.noParameters)~=PARAMETERS.noParameters,
    uicontrol(OptimGuiHandle,'Style','text',...
	      'Units','normalized',...
	      'Position',[35 30 30 10]/100,...
	      'String','The number of must an integer');
    return
  elseif PARAMETERS.noParameters<1,
    uicontrol(OptimGuiHandle,'Style','text',...
	      'Units','normalized',...
	      'Position',[35 30 30 10]/100,...
	      'String','The number of parameters must be >=1');
    return
  elseif PARAMETERS.noParameters>20,
    uicontrol(OptimGuiHandle,'Style','text',...
	      'Units','normalized',...
	      'Position',[35 30 30 10]/100,...
	      'String','The number of parameters must be <=20');
    return
  end
  %
  clf
  clear noParEdit
  x0=.02;
  dx0=0.19;
  y0=0.02;
  dy0=0.05;
  yN=0.95;
  ddy0=(yN-y0-2*dy0)/(PARAMETERS.noParameters-1);
  x1=x0;
  dx1=.15;
  x2=x1+dx1+0.01;
  dx2=dx1;
  x3=x2+dx2+0.02;
  x4=x3+0.01;
  global NameEdit DefaultEdit
  uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[x1 y0+yN-dy0 dx1 dy0],...
      'String','Parameter Name');
  uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[x2 y0+yN-dy0 dx2 dy0],...
      'String','Initial Guess');
   for i=1:PARAMETERS.noParameters,
      NameEdit(i)=uicontrol(OptimGuiHandle,'Style','edit',...
         'Units','normalized','HorizontalAlignment','right',...
         'Position',[x1 y0+(PARAMETERS.noParameters-i)*ddy0 dx1 dy0]);
      DefaultEdit(i)=uicontrol(OptimGuiHandle,'Style','edit',...
         'Units','normalized','HorizontalAlignment','right',...
         'Position',[x2 y0+(PARAMETERS.noParameters-i)*ddy0 dx2 dy0]);
   end
   uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[36 73 28 17]/100,...
      'String','Provide parameter names and initial guesses for the parameters. If the initial guess is not a valid number or if it is not given, it will be set to unity.');
   uicontrol(OptimGuiHandle,'Style','text',...
      'Units','normalized',...
      'Position',[56 43 28 10]/100,...
      'String','Provide function names for the criteria function.');
   
   global FunNameEdit;
   
   FunNameEdit=uicontrol(OptimGuiHandle,'Style','edit',...
      'Units','normalized',...
      'Position',[56 35 28 5]/100,...
      'String','');   
   uicontrol(OptimGuiHandle,'Style','pushbutton',...
      'Units','normalized',...
      'Position',[80 2 15 5]/100,...
      'String','Done!',...
      'CallBack','initLsOptGui(''Done'')');
      
elseif strcmp(cmdStr,'Done')
   global FunNameEdit PARAMETERS
   PARAMETERS.function=get(FunNameEdit,'String');
   if length(PARAMETERS.function)==0,
      warning('The function name is empty!');
   elseif exist(PARAMETERS.function)==2,
      % Detta funkar inte!!!
      warning(['The function ''' PARAMETERS.function ''' does not exist!']);
   end
   PARAMETERS.plotFunction='';
   global NameEdit DefaultEdit
   PARAMETERS.choiceVector=[];
   for i=1:PARAMETERS.noParameters,
      PARAMETERS.names{i}=get(NameEdit(i),'String');
      tmpVal=str2num(get(DefaultEdit(i),'String'));
      if length(tmpVal)==0,
         PARAMETERS.default(i)=1;
      else
         PARAMETERS.default(i)=tmpVal;
      end
      PARAMETERS.choiceVector=[PARAMETERS.choiceVector i];
   end
   PARAMETERS.current=PARAMETERS.default;
   PARAMETERS.noOptSteps=10;
   lsoptgui('Initialize');
else
   error(['Unknown input string to the function: ' cmdStr]);
end